/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TUGAS;

/**
 *
 * @author yanda
 */
public class LoginBankNings extends javax.swing.JFrame {

    /**
     * Creates new form BankRuptLogin
     */
    public LoginBankNings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        go = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("INPUT PIN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 90, 80, 17);
        getContentPane().add(password);
        password.setBounds(250, 110, 210, 40);

        go.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        go.setText("CONFIRM");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        getContentPane().add(go);
        go.setBounds(300, 160, 108, 30);

        jLabel6.setText("BANK NING'S");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 10, 80, 10);

        jLabel7.setText("SAWOJAJAR, KEDUNGKANDANG, MALANG");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 30, 220, 10);

        jLabel8.setText("JL. DANAU RANAU G6/B2, DEPAN SMK TELKOM MALANG, KODE POS 63159");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 50, 370, 10);

        jLabel9.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 60, 780, 14);

        jLabel10.setText("----------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 70, 780, 10);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("LOGIN");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 10, 60, 20);

        setBounds(0, 0, 787, 234);
    }// </editor-fold>//GEN-END:initComponents

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        if(password.getText().trim().equals("1234")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Selamat Datang");
          new HomeBankNings().setVisible(true);
        }else{
            javax.swing.JOptionPane.showMessageDialog(null, "Maaf PIN yang anda masukan salah, Coba Lagi");
        }
        this.dispose();
    }//GEN-LAST:event_goActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginBankNings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginBankNings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginBankNings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginBankNings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginBankNings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField password;
    // End of variables declaration//GEN-END:variables
}
